quizlet_easy = [
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Who created the digital distribution platform Steam?", "correct_answer": "Valve",
     "incorrect_answers": ["Pixeltail Games", "Ubisoft", "Electronic Arts"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "Igneous rocks are formed by excessive heat and pressure.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "League of Legends, DOTA 2, Smite and Heroes of the Storm are all part of which game genre?",
     "correct_answer": "Multiplayer Online Battle Arena (MOBA)",
     "incorrect_answers": ["Real Time Strategy (RTS)", "First Person Shooter (FPS)", "Role Playing Game (RPG)"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Who had a 1969 top 5 hit with the song,  &#039;A Boy Named Sue&#039;?",
     "correct_answer": "Johnny Cash", "incorrect_answers": ["Bob Dylan", "Willie Nelson", "Kris Kristofferson"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion "
                 "in stock.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is the scientific name for modern day humans?", "correct_answer": "Homo Sapiens",
     "incorrect_answers": ["Homo Ergaster", "Homo Erectus", "Homo Neanderthalensis"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The programming language &quot;Python&quot; is based off a modified version of "
                 "&quot;JavaScript&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Finish these lyrics from the 2016 song &quot;Panda&quot; by Desiigner: &quot;I got broads in "
                 "_______&quot;.",
     "correct_answer": "Atlanta", "incorrect_answers": ["Savannah", "Augusta", "Marietta"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Which eSports team came first place in The International Dota 2 Championship 2016?",
     "correct_answer": "Wings Gaming", "incorrect_answers": ["Digital Chaos", "Evil Geniuses", "Fnatic"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What is the domain name for the country Tuvalu?", "correct_answer": ".tv",
     "incorrect_answers": [".tu", ".tt", ".tl"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the nickname of the US state of California?", "correct_answer": "Golden State",
     "incorrect_answers": ["Sunshine State", "Bay State", "Treasure State"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What was the subject of the 2014 song &quot;CoCo&quot; by American rapper O. T. Genasis?",
     "correct_answer": "Cocaine",
     "incorrect_answers": ["Conan O&#039;Brien", "Cobalt(II) carbonate", "Coconut cream pie"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What&#039;s the Team Fortress 2 Scout&#039;s city of origin?", "correct_answer": "Boston",
     "incorrect_answers": ["Sydney", "Detroit", "New York"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What company created and developed the game &quot;Overwatch&quot;?",
     "correct_answer": "Blizzard Entertainment", "incorrect_answers": ["Valve", "Hi-Rez Studios", "Gearbox Software"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
     "question": "Deadpool&#039;s identity is Slade Wilson.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What was the original name of Crash Bandicoot?", "correct_answer": "Willie Wombat",
     "incorrect_answers": ["Coco Bandicoot", "Marvelous Mole", "Wally Wombat"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Who is the leader of Team Instinct in Pok&eacute;mon Go?", "correct_answer": "Spark",
     "incorrect_answers": ["Candela", "Blanche", "Willow"]},
    {"category": "History", "type": "multiple", "difficulty": "easy",
     "question": "Who was the Prime Minister of Japan when Japan declared war on the US?",
     "correct_answer": "Hideki Tojo",
     "incorrect_answers": ["Michinomiya Hirohito", "Isoroku Yamamoto", "Fumimaro Konoe"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is Grumpy Cat&#039;s real name?", "correct_answer": "Tardar Sauce",
     "incorrect_answers": ["Sauce", "Minnie", "Broccoli"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which American-owned brewery led the country in sales by volume in 2015?",
     "correct_answer": "D. G. Yuengling and Son, Inc",
     "incorrect_answers": ["Anheuser Busch", "Boston Beer Company", "Miller Coors"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In Super Mario Bros., who informs Mario that the princess is in another castle?",
     "correct_answer": "Toad", "incorrect_answers": ["Luigi", "Yoshi", "Bowser"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "A Saxophone is a brass instrument.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy", "question": "What team won the 2016 MLS Cup?",
     "correct_answer": "Seattle Sounders", "incorrect_answers": ["Colorado Rapids", "Toronto FC", "Montreal Impact"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "In 2006, which band released their debut album &quot;A Fever You Can&#039;t Sweat Out&quot;?",
     "correct_answer": "Panic! At the Disco",
     "incorrect_answers": ["Twenty One Pilots", "My Chemical Romance", "Fall Out Boy"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a "
                 "goal.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "In Star Trek: The Next Generation, what is the name of Data&#039;s cat?", "correct_answer": "Spot",
     "incorrect_answers": ["Mittens", "Tom", "Kitty"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Cats have whiskers under their legs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy", "question": "What is the capital of Spain?",
     "correct_answer": "Madrid", "incorrect_answers": ["Barcelona", "Sevilla", "Toledo"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the planet that the Doctor from television series &quot;Doctor Who&quot; comes "
                 "from?",
     "correct_answer": "Gallifrey", "incorrect_answers": ["Sontar", "Skaro", "Mondas"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In &quot;Overwatch&quot;, which hero is able to wallride?", "correct_answer": "Lucio",
     "incorrect_answers": ["Reinhardt", "Sombra", "Mercy"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Hungary is the only country in the world beginning with H.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What machine element is located in the center of fidget spinners?",
     "correct_answer": "Bearings", "incorrect_answers": ["Axles", "Gears", "Belts"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the main protagonist in &quot;Xenoblade Chronicles&quot;?",
     "correct_answer": "Shulk", "incorrect_answers": ["Reyn", "Fiora", "Dunban"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Art", "type": "multiple", "difficulty": "easy", "question": "Who painted The Starry Night?",
     "correct_answer": "Vincent van Gogh", "incorrect_answers": ["Pablo Picasso", "Leonardo da Vinci", "Michelangelo"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "Which noble gas has the lowest atomic number?", "correct_answer": "Helium",
     "incorrect_answers": ["Neon", "Argon", "Krypton"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What nuts are used in the production of marzipan?", "correct_answer": "Almonds",
     "incorrect_answers": ["Peanuts", "Walnuts", "Pistachios"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "How long is an IPv6 address?", "correct_answer": "128 bits",
     "incorrect_answers": ["32 bits", "64 bits", "128 bytes"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What 1970&#039;s American ballad referred to the 1959 plane crash as the &quot;the day the music "
                 "died&quot;?",
     "correct_answer": "American Pie",
     "incorrect_answers": ["Kentucky Rain", "I Will Always Love You", "Rock &#039;n&#039; Roll Suicide"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Which boxer was banned for taking a bite out of Evander Holyfield&#039;s ear in 1997?",
     "correct_answer": "Mike Tyson", "incorrect_answers": ["Roy Jones Jr.", "Evander Holyfield", "Lennox Lewis"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What Led Zeppelin album contains &quot;Stairway to Heaven&quot;?",
     "correct_answer": "Led Zeppelin IV",
     "incorrect_answers": ["Houses of the Holy", "Physical Graffiti", "Led Zeppelin III"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the talking cat in Persona 5?", "correct_answer": "Morgana",
     "incorrect_answers": ["Teddie", "Marie", "Ryuji"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
     "question": "What lies at the center of our galaxy?", "correct_answer": "A black hole",
     "incorrect_answers": ["A wormhole", "A supernova", "A quasar"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What Ultimate does Makoto Naegi, protagonist of Danganronpa: Trigger Happy Havoc, have? ",
     "correct_answer": "Ultimate Lucky Student",
     "incorrect_answers": ["Ultimate Unlucky Student", "Ultimate Detective", "Ultimate Runner"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?",
     "correct_answer": "Helicopter", "incorrect_answers": ["Stealth Blimp", "Jet", "Space Capsule"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In the video game &quot;Postal 2&quot;, what is the name of Postal Dude&#039;s dog?",
     "correct_answer": "Champ", "incorrect_answers": ["Snoopy", "Krotchy", "Duke"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.", "correct_answer": "True",
     "incorrect_answers": ["False"]}]
quizlet_medium = [
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
     "question": "From what show is the character &quot;James Doakes&quot;? ", "correct_answer": "Dexter",
     "incorrect_answers": ["Marvel&#039;s Daredevil", "Boardwalk Empire", "The Walking Dead"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "In the 1984 movie &quot;The Terminator&quot;, what model number is the Terminator portrayed by "
                 "Arnold Schwarzenegger?",
     "correct_answer": "T-800", "incorrect_answers": ["I-950", "T-888", "T-1000"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
     "question": "In the original Doctor Who series (1963), fourth doctor Tom Baker&#039;s scarf was how long?",
     "correct_answer": "7 Meters", "incorrect_answers": ["10 Meters", "2 Meters", "5 Meters"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "There are no roads in & out of Juneau, Alaska.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What five letter word is the motto of the IBM Computer company?",
     "correct_answer": "Think", "incorrect_answers": ["Click", "Logic", "Pixel"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "medium",
     "question": "By what name was the author Eric Blair better known?", "correct_answer": "George Orwell",
     "incorrect_answers": ["Aldous Huxley", "Ernest Hemingway", "Ray Bradbury"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "medium",
     "question": "What was the pen name of novelist, Mary Ann Evans?", "correct_answer": "George Eliot",
     "incorrect_answers": ["George Orwell", "George Bernard Shaw", "George Saunders"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In what year was the original Sonic the Hedgehog game released?", "correct_answer": "1991",
     "incorrect_answers": ["1989", "1993", "1995"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "According to scholarly estimates, what percentage of the world population at the time died due to "
                 "Tamerlane&#039;s conquests?",
     "correct_answer": "5%",
     "incorrect_answers": ["1%", "3%", "&lt;1%"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "What is a &quot;dakimakura&quot;?", "correct_answer": "A body pillow",
     "incorrect_answers": ["A Chinese meal, essentially composed of fish", "A yoga posture",
                           "A word used to describe two people who truly love each other"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Which football player is featured on the international cover version of the video game FIFA 16?",
     "correct_answer": "Lionel Messi", "incorrect_answers": ["Cristiano Ronaldo", "Wayne Rooney", "David Beckham"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which of these artists has NOT been a member of dancehall group Major Lazer?",
     "correct_answer": "Skrillex", "incorrect_answers": ["Diplo", "Jillionaire", "Walshy Fire"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "Joseph Stalin had a criminal past doing what?", "correct_answer": "Robbing Trains",
     "incorrect_answers": ["Murder for Hire", "Tax Evasion", "Identity Fraud"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "What does the yellow diamond on the NFPA 704 fire diamond represent?", "correct_answer": "Reactivity",
     "incorrect_answers": ["Health", "Flammability", "Radioactivity"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Which of these is NOT the name of a team leader in Pok&eacute;mon GO?", "correct_answer": "Leif",
     "incorrect_answers": ["Blanche", "Spark", "Candela"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "What were the first states to break away from Yugoslavia?", "correct_answer": "Slovenia, Croatia",
     "incorrect_answers": ["Macedonia, Montenegro", "Slovenia, Macedonia", "Montenegro, Slovenia"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "When was Nintendo founded?", "correct_answer": "September 23rd, 1889",
     "incorrect_answers": ["October 19th, 1891", "March 4th, 1887", "December 27th, 1894"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "How fast is USB 3.1 Gen 2 theoretically?", "correct_answer": "10 Gbps",
     "incorrect_answers": ["5 Gbps", "8 Gbps", "1 Gbps"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "Darth Vader&#039;s famous reveal to Luke is iconic. But which of these is the right one?",
     "correct_answer": "&quot;No. I am your father.&quot;",
     "incorrect_answers": ["&quot;Luke, I am your father.&quot;", "&quot;You&#039;re wrong. "
                                                                  "I am your father.&quot;",
                           "&quot;The truth is that I am your father.&quot;"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which operating system was released first?", "correct_answer": "Mac OS",
     "incorrect_answers": ["Windows", "Linux", "OSv2"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the Greek god of blacksmiths?", "correct_answer": "Hephaestus",
     "incorrect_answers": ["Dyntos", "Vulcan", "Artagatus"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "What is radiation measured in?", "correct_answer": "Gray ",
     "incorrect_answers": ["Watt", "Decibel", "Kelvin"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
     "question": "Nickelodeon rejected the pilot to Adventure Time.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In what year was &quot;Super Mario Sunshine&quot; released?", "correct_answer": "2002",
     "incorrect_answers": ["2003", "2000", "2004"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the device that allows for infinite energy in the anime &quot;Dimension "
                 "W&quot;?",
     "correct_answer": "Coils", "incorrect_answers": ["Wires", "Collectors", "Tesla"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the game Pok&eacute;mon Conquest, which warlord is able to bond with Zekrom "
                 "and a shiny Rayquazza?",
     "correct_answer": "Nobunaga", "incorrect_answers": ["The Player", "Oichi", "Hideyoshi"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the game Pok&eacute;mon Conquest, how many kingdoms make up the region of Ransei?",
     "correct_answer": "17", "incorrect_answers": ["18", "15", "16"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "In 1961, an American B-52 aircraft crashed and nearly detonated two 4mt "
                 "nuclear bombs over which US city?",
     "correct_answer": "Goldsboro, North Carolina",
     "incorrect_answers": ["Hicksville, New York", "Jacksonville, Florida", "Conway, Arkansas"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the beginning of the game &quot;Sonic Adventure&quot;, what color "
                 "Chaos Emerald does Tails own?",
     "correct_answer": "Purple", "incorrect_answers": ["Red", "Green", "Blue"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the &quot;Portal&quot; series, who was Cave Johnson&#039;s personal assistant?",
     "correct_answer": "Caroline", "incorrect_answers": ["Heather", "Melissa", "Jane"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
     "question": "In &quot;The Simpsons&quot;, what is the real name of &quot;Comic Book Guy&quot;?",
     "correct_answer": "Jeff Albertson", "incorrect_answers": ["Comic Book Guy", "Edward Stone", "Jack Richardson"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Where does &quot;The Legend of Zelda: Majora&#039;s Mask&quot; take place?",
     "correct_answer": "Termina", "incorrect_answers": ["Hyrule", "Gysahl", "Besaid"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "In Mulan (1998), who is the leader of the Huns?", "correct_answer": "Shan Yu",
     "incorrect_answers": ["Chien-Po", "Li Shang", "Fa Zhou"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "What character in the Winnie the Pooh films was added by Disney and does not appear in the original "
                 "books?",
     "correct_answer": "Gopher", "incorrect_answers": ["Tigger", "Heffalumps", "Rabbit"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which of these songs is NOT in The Beatles&#039; album &quot;Sgt. Pepper&#039;s Lonely Hearts Club "
                 "Band&quot;?",
     "correct_answer": "Strawberry Fields Forever",
     "incorrect_answers": ["Getting Better", "Fixing a Hole", "Lucy in the Sky with Diamonds"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which is the world&#039;s longest river?", "correct_answer": "Nile",
     "incorrect_answers": ["Missouri", "Amazon", "Yangtze"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "Which 90&#039;s comedy cult classic features cameos appearances from Meat Loaf, Alice Cooper and "
                 "Chris Farley?",
     "correct_answer": "Wayne&#039;s World",
     "incorrect_answers": ["Bill &amp; Ted&#039;s Excellent Adventure", "Dumb and Dumber",
                           "Austin Powers: International Man of Mystery"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "A statue of Charles Darwin sits in what London museum?", "correct_answer": "Natural History Museum",
     "incorrect_answers": ["Tate", "British Museum", "Science Museum"]},
    {"category": "Animals", "type": "multiple", "difficulty": "medium",
     "question": "What is the collective noun for rats?", "correct_answer": "Mischief",
     "incorrect_answers": ["Pack", "Race", "Drift"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "Which of these 1900s tanks were designed and built BEFORE the others?",
     "correct_answer": "Renault FT", "incorrect_answers": ["M4 Sherman", " Panzer IV", "Cromwell "]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
     "question": "What year did Gerald Ford Become President?", "correct_answer": "1974",
     "incorrect_answers": ["1977", "1973", "1969"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "Who assassinated Archduke Franz Ferdinand?",
     "correct_answer": "Gavrilo Princip",
     "incorrect_answers": ["Nedeljko \u010cabrinovi\u0107",
                           "Oskar Potiorek", "Ferdinand Cohen-Blind"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which of these is not a member of the virtual band Gorillaz?", "correct_answer": "Phi Cypher",
     "incorrect_answers": ["Murdoc Niccals", "Noodle", "Russel Hobbs"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "multiple", "difficulty": "medium",
     "question": "What animated internet character is known to answer emails with his boxing gloves?",
     "correct_answer": "Strong Bad", "incorrect_answers": ["Strong Sad", "Strong Mad", "Strong Glad"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the race horse that Tony Soprano becomes attached to?",
     "correct_answer": "Pie-O-My", "incorrect_answers": ["Man o&#039; war", "Bada Bing", "Honest Earnings"]}]
quizlet_hard = [
    {"category": "Animals", "type": "multiple", "difficulty": "hard",
     "question": "What was the name of the Ethiopian Wolf before they knew it was related to wolves?",
     "correct_answer": "Simien Jackel",
     "incorrect_answers": ["Ethiopian Coyote", "Amharic Fox", "Canis Simiensis"]},
    {"category": "Entertainment: Film", "type": "multiple",
     "difficulty": "hard",
     "question": "Which was the first of Alfred Hitchcock&#039;s movies to be filmed in colour?",
     "correct_answer": "Rope",
     "incorrect_answers": ["Psycho", "Vertigo", "Rebecca"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "What is the name of the virus that infected New York in Tom Clancy&#039;s The Division?",
     "correct_answer": "Dollar Flu",
     "incorrect_answers": ["Ebola", "Red Poison", "Smallpox"]},
    {"category": "Science: Computers", "type": "multiple",
     "difficulty": "hard",
     "question": "What was the name of the security vulnerability found in Bash in 2014?",
     "correct_answer": "Shellshock",
     "incorrect_answers": ["Heartbleed", "Bashbug", "Stagefright"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Which of these island countries is located in the Caribbean?",
     "correct_answer": "Barbados",
     "incorrect_answers": ["Fiji", "Maldives", "Seychelles"]},
    {"category": "Entertainment: Books", "type": "multiple",
     "difficulty": "hard",
     "question": "In the Harry Potter universe, who does Draco Malfoy end up marrying?",
     "correct_answer": "Astoria Greengrass",
     "incorrect_answers": ["Pansy Parkinson", "Millicent Bulstrode", "Hermione Granger"]},
    {"category": "Entertainment: Books", "type": "multiple",
     "difficulty": "hard",
     "question": "What is Ron Weasley&#039;s middle name?",
     "correct_answer": "Bilius",
     "incorrect_answers": ["Arthur", "John", "Dominic"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "hard",
     "question": "Unturned originally started as a Roblox game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple",
     "difficulty": "hard",
     "question": "The words &quot;bungalow&quot; and &quot;shampoo&quot; originate from the "
                 "languages of which country?",
     "correct_answer": "India",
     "incorrect_answers": ["Papua New Guinea", "Ethiopia", "China"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of the following commercial vehicles from Grand Theft Auto IV did NOT reappear in Grand Theft "
                 "Auto V?",
     "correct_answer": "Steed",
     "incorrect_answers": ["Mule", "Benson", "Pony"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "How many copies of the notorious E.T. game for the Atari 2600 did Atari end up selling?",
     "correct_answer": "1.5 Million",
     "incorrect_answers": ["1 Million", "250 Thousand", "Less than 250 Thousand"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "In 2012 the German-speaking microstate &quot;Liechtenstein&quot; in Central Europe had a population "
                 "of how many inhabitants?",
     "correct_answer": "36,600",
     "incorrect_answers": ["2,400", "90,000", "323,400"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard", "question": "When was Steam first released?",
     "correct_answer": "2003",
     "incorrect_answers": ["2004", "2011", "2007"]},
    {"category": "Entertainment: Music", "type": "multiple",
     "difficulty": "hard",
     "question": "Who won the 1989 Drum Corps International championships?",
     "correct_answer": "Santa Clara Vanguard",
     "incorrect_answers": ["Blue Devils", "The Academy", "The Bluecoats"]},
    {"category": "History", "type": "multiple", "difficulty": "hard",
     "question": "When did Canada leave the confederation to become their own nation?",
     "correct_answer": "July 1st, 1867",
     "incorrect_answers": ["July 1st, 1763", "July 1st, 1832", "July 1st, 1902"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "Which souls game was not directed by Hidetaka Miyazaki?",
     "correct_answer": "Dark Souls 2",
     "incorrect_answers": ["Demon Souls", "Dark Souls", "Dark Souls 3"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "multiple", "difficulty": "hard",
     "question": "What is the last line muttered in the anime film &quot;The End of Evangelion&quot;?",
     "correct_answer": "&quot;How disgusting.&quot;", "incorrect_answers": [
        "&quot;Idiot, I won&#039;t let you kill me!&quot;",
        "&quot;Nothing.&quot;", "&quot;Goddammit, Shinji.&quot;"]},
    {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
     "question": "Which car is the first mass-produced hybrid vehicle?",
     "correct_answer": "Toyota Prius",
     "incorrect_answers": ["Chevrolet Volt", "Honda Fit", "Peugeot 308 R HYbrid"]},
    {"category": "Celebrities", "type": "multiple", "difficulty": "hard",
     "question": "What was the religion of famous singer &quot;Freddie Mercury&quot;?",
     "correct_answer": "Zoroastrianism",
     "incorrect_answers": ["Paganism", "Ashurism", "Judaism"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "The Hunua Ranges is located in...",
     "correct_answer": "New Zealand",
     "incorrect_answers": ["Nepal", "China", "Mexico"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the most populous Muslim-majority nation in 2010?",
     "correct_answer": "Indonesia",
     "incorrect_answers": ["Saudi Arabia", "Iran", "Sudan"]},
    {"category": "Science: Mathematics", "type": "multiple",
     "difficulty": "hard",
     "question": "The decimal number 31 in hexadecimal would be what?",
     "correct_answer": "1F", "incorrect_answers": ["3D", "2E", "1B"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "In TF2 Lore, what are the names of the Heavy&#039;s younger sisters?",
     "correct_answer": "Yana and Bronislava",
     "incorrect_answers": ["Gaba and Anna", "Yanna and Gaba",
                           "Anna and Bronislava"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What North American tourist attraction is served by the &quot;Maid of the Mist&quot; tour company?",
     "correct_answer": "Niagara Falls",
     "incorrect_answers": ["Whistler, British Columbia", "Disney World",
                           "Yosemite National Park"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the second-largest city in Lithuania?",
     "correct_answer": "Kaunas",
     "incorrect_answers": ["Panev\u0117\u017eys", "Vilnius", "Klaip\u0117da"]},
    {"category": "Science & Nature", "type": "multiple",
     "difficulty": "hard",
     "question": "What does the term &quot;isolation&quot; refer to in microbiology?",
     "correct_answer": "The separation of a strain from a natural, mixed population of living microbes",
     "incorrect_answers": ["A lack of nutrition in microenviroments", "The nitrogen level in soil",
                           "Testing effects of certain microorganisms in an isolated enviroments, such as caves"]},
    {"category": "Entertainment: Television", "type": "multiple",
     "difficulty": "hard",
     "question": "In &quot;Star Trek&quot;, what sauce is commonly used by Klingons on bregit lung?",
     "correct_answer": "Grapok sauce",
     "incorrect_answers": ["Gazorpazorp pudding", "Sweet chili sauce", "Grapork sauce"]},
    {"category": "Sports", "type": "multiple", "difficulty": "hard",
     "question": "What is the full name of the footballer &quot;Cristiano Ronaldo&quot;?",
     "correct_answer": "Cristiano Ronaldo dos Santos Aveiro",
     "incorrect_answers": ["Cristiano Ronaldo los Santos Diego", "Cristiano Armando Diego Ronaldo",
                           "Cristiano Luis Armando Ronaldo"]},
    {"category": "Science: Mathematics", "type": "boolean",
     "difficulty": "hard",
     "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to "
                 "evaluate limits with indeterminations.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple",
     "difficulty": "hard",
     "question": "Dutch computer scientist Mark Overmars is known for creating which game development engine?",
     "correct_answer": "Game Maker",
     "incorrect_answers": ["Stencyl", "Construct", "Torque 2D"]},
    {"category": "General Knowledge", "type": "multiple",
     "difficulty": "hard",
     "question": "Virtual reality company Oculus VR lost which of it&#039;s co-founders in a freak car accident in "
                 "2013?",
     "correct_answer": "Andrew Scott Reisse",
     "incorrect_answers": ["Nate Mitchell", "Jack McCauley", "Palmer Luckey"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "In &quot;Call Of Duty: Zombies&quot;, which weapon does NOT deal any damage?",
     "correct_answer": "31-79 JGb215",
     "incorrect_answers": ["Sliquifier", "V-R11", "Wunderwaffe DG-2"]},
    {"category": "Science & Nature", "type": "multiple",
     "difficulty": "hard", "question": "How long is a light-year?",
     "correct_answer": "9.461 Trillion Kilometres",
     "incorrect_answers": ["1 AU", "105.40 Earth-years", "501.2 Million Miles"]},
    {"category": "Politics", "type": "multiple", "difficulty": "hard",
     "question": "In June 2017, Saudi Arabia and Egypt broke off ties with which country over its supposed support "
                 "for terrorism?",
     "correct_answer": "Qatar",
     "incorrect_answers": ["Bahrain", "United States of America", "Russia"]},
    {"category": "Entertainment: Board Games", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of these cards from &quot;Magic: The Gathering&quot; has a flavor text that begins with "
                 "&quot;Oi oi oi&quot;?",
     "correct_answer": "Uthden Troll",
     "incorrect_answers": ["Lotleth Troll", "Albino Troll", "Harvester Troll"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "multiple", "difficulty": "hard",
     "question": "Which animation studio produced &quot;Log Horizon&quot;?",
     "correct_answer": "Satelite",
     "incorrect_answers": ["Sunrise", "Xebec", "Production I.G"]},
    {"category": "Science & Nature", "type": "multiple",
     "difficulty": "hard",
     "question": "Coulrophobia is the irrational fear of what?",
     "correct_answer": "Clowns",
     "incorrect_answers": ["Cemeteries", "Needles", "Tunnels"]},
    {"category": "Science: Gadgets", "type": "multiple",
     "difficulty": "hard",
     "question": "Which round does a WW2 M1 Garand fire?",
     "correct_answer": ".30-06",
     "incorrect_answers": [".308", "7.62", "7.62x51mm"]},
    {"category": "Celebrities", "type": "multiple", "difficulty": "hard",
     "question": "Who was Donald Trump&#039;s first wife?",
     "correct_answer": "Ivana Zeln&iacute;\u010dkov&aacute;",
     "incorrect_answers": ["Melania Knauss", "Marla Maples", "Nancy Davis"]},
    {"category": "History", "type": "multiple", "difficulty": "hard",
     "question": "Toussaint Louverture led a successful slave revolt in which country?",
     "correct_answer": "Haiti",
     "incorrect_answers": ["France", "Cuba", "United States"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Into which basin does the Jordan River flow into?",
     "correct_answer": "Dead Sea",
     "incorrect_answers": ["Aral Sea", "Caspian Sea", "Salton Sea"]},
    {"category": "Science: Computers", "type": "multiple",
     "difficulty": "hard",
     "question": "According to DeMorgan&#039;s Theorem, the Boolean expression (AB)&#039; is equivalent to:",
     "correct_answer": "A&#039; + B&#039;",
     "incorrect_answers": ["A&#039;B + B&#039;A", "A&#039;B&#039;", "AB&#039; + AB"]},
    {"category": "General Knowledge", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of these cities does NOT have a United States Minting location?",
     "correct_answer": "St. Louis, MO",
     "incorrect_answers": ["San Fransisco, CA", "Philidelphia, PA", "West Point, NY"]},
    {"category": "Entertainment: Musicals & Theatres", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of these plays was famously first performed posthumously after the playwright committed "
                 "suicide?",
     "correct_answer": "4.48 Psychosis",
     "incorrect_answers": ["Hamilton", "Much Ado About Nothing", "The Birthday Party"]},
    {"category": "History", "type": "multiple", "difficulty": "hard",
     "question": "Which of these theoretical phycisists first predicted the existence of antimatter?",
     "correct_answer": "Paul Dirac",
     "incorrect_answers": ["Niels Bohr", "Albert Einstein", "Werner Heisenberg"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "hard",
     "question": "In Geometry Dash, what is level 13?",
     "correct_answer": "Electroman Adventures",
     "incorrect_answers": ["Theory of Everything", "Clubstep ", "Clutterfunk"]},
    {"category": "Science: Computers", "type": "multiple",
     "difficulty": "hard",
     "question": "Which of these Cherry MX mechanical keyboard switches is both tactile and clicky?",
     "correct_answer": "Cherry MX Blue",
     "incorrect_answers": ["Cherry MX Black", "Cherry MX Red", "Cherry MX Brown"]},
    {"category": "Entertainment: Film", "type": "multiple",
     "difficulty": "hard",
     "question": "What was the wifi password given to Stephen Strange in Doctor Strange?",
     "correct_answer": "Shambala",
     "incorrect_answers": ["Peace", "Ancient", "Chakra"]},
    {"category": "Sports", "type": "multiple", "difficulty": "hard",
     "question": "In Canadian football, scoring a rouge is worth how many points?",
     "correct_answer": "1", "incorrect_answers": ["2", "3", "4"]},
    {"category": "Politics", "type": "multiple", "difficulty": "hard",
     "question": "Who is the only US president to serve two non-consecutive terms in office?",
     "correct_answer": "Grover Cleveland",
     "incorrect_answers": ["James K. Polk", "Franklin D. Roosevelt", "Thomas Jefferson"]}]
